# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
print(np.__version__)
print(np.show_config())


1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/arwa0/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/arwa0/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/arwa0/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/arwa0/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/arwa0/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/arwa0/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/arwa0/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/arwa0/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
import numpy as np

# الطريقة 1: باستخدام np.random.rand (قيم بين 0 و 1)
a = np.random.rand(2, 3, 5)
print(a)

# الطريقة 2: باستخدام np.random.randn (قيم من التوزيع الطبيعي)
a = np.random.randn(2, 3, 5)
print(a)

# الطريقة 3: باستخدام np.random.randint (قيم صحيحة بين 0 و 100)
a = np.random.randint(0, 100, (2, 3, 5))


[[[0.06829842 0.84396836 0.24576877 0.17840056 0.79041199]
  [0.97961866 0.27056636 0.3773015  0.49928357 0.39576659]
  [0.5688336  0.0049197  0.8359881  0.99973822 0.35377429]]

 [[0.54177899 0.07952951 0.67773981 0.45081602 0.64071923]
  [0.14656488 0.5171685  0.97262099 0.6061738  0.40453216]
  [0.99079822 0.50826388 0.67860479 0.36031917 0.69032802]]]
[[[-1.66437058e-01 -1.67629629e-03 -7.75554388e-03  1.13040622e+00
    5.51493353e-02]
  [-2.01181420e-01  1.13024299e-01 -1.19992837e+00  6.33610221e-01
   -6.46748816e-01]
  [ 4.13534809e-01  1.12775525e+00  3.53772899e-01  2.78739296e+00
    2.21246385e+00]]

 [[ 1.52354581e-01  8.12260387e-01 -5.89895237e-01  1.50605898e-02
   -2.60027969e+00]
  [-6.54152218e-01  1.06857255e+00 -5.19323921e-01  9.06817759e-01
   -7.49969193e-01]
  [-4.74234849e-01 -8.46911195e-01  7.86779137e-01  5.91823337e-01
   -9.20793508e-03]]]



### 4. Print a.


In [9]:
print(a)


[[[77 67 95  4 31]
  [61 80 48 41 48]
  [49 85 13 51 25]]

 [[36 77 70 13 35]
  [15 75 10 94 13]
  [55 18 92 50 14]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [10]:
b = np.ones((5, 2, 3))
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 6. Print b.


In [12]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [13]:
print(a.size)  # عدد العناصر في المصفوفة a
print(b.size)  # عدد العناصر في المصفوفة b

# التحقق مما إذا كان لهما نفس الحجم
print(a.size == b.size)


30
30
True



### 8. Are you able to add a and b? Why or why not?


SyntaxError: invalid syntax (1099919384.py, line 3)



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [34]:
c = b.transpose(1, 2, 0)  # إعادة ترتيب الأبعاد لتصبح (2,3,5)
print(c.shape)  # التأكد أن الشكل أصبح (2,3,5)
### *10. محاولة جمع a و c، وتخزين النتيجة في d. لماذا يعمل الجمع الآن؟*  
python
d = a + c


NameError: name 'b' is not defined


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [31]:
def setA(value):
    print "Before assignment, a is %d" % (a)
    a = value
    print "Inside setA, a is now %d" % (a)

SyntaxError: invalid syntax (1108385129.py, line 2)


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [29]:
### [your code here]




### 12. Multiply a and c. Assign the result to e.


In [30]:
### [your code here]




### 13. Does e equal to a? Why or why not?


In [31]:
### [your code here]





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


IndentationError: expected an indented block (3787583846.py, line 6)


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [34]:
### [your code here]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [35]:
### [your code here]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]