# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
print("NumPy Version:", np.__version__) # طباعة إصدار NumPy
np.show_config()

NumPy Version: 1.26.4
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.8",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT=1 DYNAMIC_ARCH=1 DYN

C:\Users\arwa0\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
a = np.random.randint(2, size=(2, 3, 5))
a

array([[[0, 0, 0, 0, 0],
        [1, 0, 0, 1, 0],
        [0, 0, 1, 1, 0]],

       [[0, 1, 1, 0, 0],
        [0, 1, 1, 0, 1],
        [0, 1, 1, 1, 0]]])


### 4. Print a.


In [4]:
print(a)


[[[0 0 0 0 0]
  [1 0 0 1 0]
  [0 0 1 1 0]]

 [[0 1 1 0 0]
  [0 1 1 0 1]
  [0 1 1 1 0]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
b = np.ones((5, 2,3))



### 6. Print b.


In [6]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
### [your code here]
if a.size == b.size:
    print(True)
else:
    print(False)

True



### 8. Are you able to add a and b? Why or why not?


In [9]:
### [your code here]

add_arr = a + b


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [10]:
c= np.transpose(b, (1, 2, 0)) 


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [11]:
### [your code here]
d = a + c
print(d)

[[[1. 1. 1. 1. 1.]
  [2. 1. 1. 2. 1.]
  [1. 1. 2. 2. 1.]]

 [[1. 2. 2. 1. 1.]
  [1. 2. 2. 1. 2.]
  [1. 2. 2. 2. 1.]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [12]:
### [your code here]
print(a)
print(d)

[[[0 0 0 0 0]
  [1 0 0 1 0]
  [0 0 1 1 0]]

 [[0 1 1 0 0]
  [0 1 1 0 1]
  [0 1 1 1 0]]]
[[[1. 1. 1. 1. 1.]
  [2. 1. 1. 2. 1.]
  [1. 1. 2. 2. 1.]]

 [[1. 2. 2. 1. 1.]
  [1. 2. 2. 1. 2.]
  [1. 2. 2. 2. 1.]]]



### 12. Multiply a and c. Assign the result to e.


In [13]:
### [your code here]
e = a*c
e

array([[[0., 0., 0., 0., 0.],
        [1., 0., 0., 1., 0.],
        [0., 0., 1., 1., 0.]],

       [[0., 1., 1., 0., 0.],
        [0., 1., 1., 0., 1.],
        [0., 1., 1., 1., 0.]]])



### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]
# yes 



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [14]:
### [your code here]
d_max= np.max(d)
d_min= np.min(d)
d_mean= np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

2.0
1.0
1.4



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [15]:
### [your code here]
f= np.empty([2,3,5])
f

array([[[0., 0., 0., 0., 0.],
        [1., 0., 0., 1., 0.],
        [0., 0., 1., 1., 0.]],

       [[0., 1., 1., 0., 0.],
        [0., 1., 1., 0., 1.],
        [0., 1., 1., 1., 0.]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [16]:
### [your code here]
f = np.empty_like(d)
for i in range(d.shape[0]): 
    for j in range(d.shape[1]):  
        for k in range(d.shape[2]):  
            if d[i, j, k] == d_min:
               f[i, j, k] = 0
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
print(f)

[[[  0.   0.   0.   0.   0.]
  [100.   0.   0. 100.   0.]
  [  0.   0. 100. 100.   0.]]

 [[  0. 100. 100.   0.   0.]
  [  0. 100. 100.   0. 100.]
  [  0. 100. 100. 100.   0.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
#your code here
import numpy as np
d = np.random.uniform(1, 2, (2, 3, 5))
min_val = np.min(d)
max_val = np.max(d)
f = np.zeros_like(d)
f[d == min_val] = 0  
f[d == max_val] = 100  
f[(d > min_val) & (d < (min_val + (max_val - min_val) / 2))] = 25
f[(d >= (min_val + (max_val - min_val) / 2)) & (d < max_val)] = 75


In [23]:
display("Array d:", d)
display("Array f:", f)

'Array d:'

array([[[1.4484115 , 1.7506259 , 1.05541606, 1.74033379, 1.91879472],
        [1.1578611 , 1.92778681, 1.96817841, 1.17501279, 1.45344244],
        [1.25099666, 1.40743611, 1.1211123 , 1.37154496, 1.53597688]],

       [[1.61372112, 1.75489118, 1.6938665 , 1.4896549 , 1.04375552],
        [1.88443717, 1.75925873, 1.56695152, 1.62025982, 1.44589072],
        [1.49085261, 1.66241962, 1.20468197, 1.32227365, 1.5433898 ]]])

'Array f:'

array([[[ 25.,  75.,  25.,  75.,  75.],
        [ 25.,  75., 100.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  75.]],

       [[ 75.,  75.,  75.,  25.,   0.],
        [ 75.,  75.,  75.,  75.,  25.],
        [ 25.,  75.,  25.,  25.,  75.]]])

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [24]:
### [your code here]
import numpy as np
d = np.random.uniform(1, 2, (2, 3, 5))
min_val = np.min(d)
max_val = np.max(d)
f = np.empty(d.shape, dtype=object)
f[d == min_val] = "A" 
f[d == max_val] = "E"  
f[(d > min_val) & (d < (min_val + (max_val - min_val) / 2))] = "B"
f[(d >= (min_val + (max_val - min_val) / 2)) & (d < max_val)] = "D"

In [25]:
display("Array d:", d)
display("Array f:", f)

'Array d:'

array([[[1.94694153, 1.66776886, 1.60246507, 1.46025709, 1.29344827],
        [1.41094222, 1.06544742, 1.07899215, 1.39921773, 1.21867486],
        [1.12233655, 1.8947733 , 1.96961814, 1.18541972, 1.93274783]],

       [[1.75014914, 1.60784183, 1.95511255, 1.43855943, 1.36617452],
        [1.34761201, 1.83767152, 1.47272782, 1.07947666, 1.05610606],
        [1.10962863, 1.4758492 , 1.83659069, 1.31207383, 1.25633627]]])

'Array f:'

array([[['D', 'D', 'D', 'B', 'B'],
        ['B', 'B', 'B', 'B', 'B'],
        ['B', 'D', 'E', 'B', 'D']],

       [['D', 'D', 'D', 'B', 'B'],
        ['B', 'D', 'B', 'B', 'A'],
        ['B', 'B', 'D', 'B', 'B']]], dtype=object)