# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [44]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [5]:


print(np.__version__)  # طباعة إصدار NumPy
print(np.show_config())  # طباعة معلومات التكوين والإعدادات



1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/arwa0/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/arwa0/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/arwa0/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/arwa0/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/arwa0/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/arwa0/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/arwa0/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/arwa0/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [7]:


# الطريقة 1: استخدام np.random.rand() لتوليد قيم بين 0 و 1
a = np.random.rand(2, 3, 5)
print(a)

# الطريقة 2: استخدام np.random.randn() لتوليد قيم من التوزيع الطبيعي
a = np.random.randn(2, 3, 5)
print(a)

# الطريقة 3: استخدام np.random.randint() لتوليد أعداد صحيحة عشوائية بين 0 و 100
a = np.random.randint(0, 100, (2, 3, 5))
print(a)


[[[0.83664026 0.5442634  0.48743532 0.87177182 0.06200324]
  [0.66465447 0.8508424  0.18341019 0.42564718 0.69168977]
  [0.70987254 0.05408048 0.12356238 0.36644461 0.46132054]]

 [[0.70906117 0.25462679 0.36048986 0.19652844 0.15377773]
  [0.60337073 0.73294962 0.19593232 0.55475852 0.10366191]
  [0.96706362 0.53801863 0.79338315 0.92392306 0.29386122]]]
[[[ 0.86147545 -0.90422626  1.81125781  2.04397155  0.77281096]
  [ 1.12815998 -0.27776215  0.24576906 -0.28896649 -0.56496312]
  [-0.70958628  0.88961278  0.75803769  1.33989521  0.55991679]]

 [[-0.66242042 -0.36171097  2.00145722  0.02688569 -1.1661594 ]
  [-1.52574919  0.64709582 -0.07975013  0.27649673 -0.44610824]
  [-0.55637616 -0.82769031 -0.29493742  0.59351847  0.6827159 ]]]
[[[77 22 60  2 69]
  [62 95 94 45  8]
  [32 78 16 25 68]]

 [[10 99 36 19 80]
  [37 49 40 67 94]
  [59 40 65 36 94]]]



### 4. Print a.


In [8]:
print(a)




[[[77 22 60  2 69]
  [62 95 94 45  8]
  [32 78 16 25 68]]

 [[10 99 36 19 80]
  [37 49 40 67 94]
  [59 40 65 36 94]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [10]:
b = np.ones((5, 2, 3))
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 6. Print b.


In [12]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [9]:
print(a.size)  
print(b.size) 
print(a.size == b.size)


30
30
True



### 8. Are you able to add a and b? Why or why not?


In [32]:


a = np.array([[1, 2, 3], [4, 5, 6]]) 
b = np.array([[7, 8, 9], [10, 11, 12]])  

print("شكل a:", a.shape)
print("شكل b:", b.shape)
c = a + b
print("\n", c)



شكل a: (2, 3)
شكل b: (2, 3)

 [[ 8 10 12]
 [14 16 18]]




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [37]:
# طباعة أشكال المصفوفات a و b
print("شكل a:", a.shape)
print("شكل b:", b.shape)

# محاولة جمع المصفوفات
try:
    result = a + b
    print("تمت عملية الجمع بنجاح!")
    print(result)
except ValueError as e:
    print("خطأ أثناء الجمع:", e)




شكل a: (2, 3)
شكل b: (2, 3)
تمت عملية الجمع بنجاح!
[[ 8 10 12]
 [14 16 18]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [38]:
d_max = np.max(d)  
d_min = np.min(d)  
d_mean = np.mean(d)  
print("Maximum value (d_max):", d_max)
print("Minimum value (d_min):", d_min)
print("Mean value (d_mean):", d_mean)


NameError: name 'd' is not defined


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [34]:
print("Array a:\n", a)
print("Array d:\n", d)
print("Difference (d - a):\n", d - a)


Array a:
 [[1 2 3]
 [4 5 6]]


NameError: name 'd' is not defined


### 12. Multiply a and c. Assign the result to e.


In [39]:
print("Array e:\n", e)


NameError: name 'e' is not defined



### 13. Does e equal to a? Why or why not?


In [23]:
# حساب القيم المطلوبة
d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)

# تطبيق الشروط على القيم في d وتحديث القيم في f
f[d == d_min] = 0
f[(d > d_min) & (d < d_mean)] = 25
f[d == d_mean] = 50
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_max] = 100




NameError: name 'd' is not defined



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [45]:

d_max = np.max(d)  
d_min = np.min(d)  
d_mean = np.mean(d)  
print("أكبر قيمة في d:", d_max)
print("أصغر قيمة في d:", d_min)
print("متوسط القيم في d:", d_mean)


NameError: name 'd' is not defined


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [42]:
# إنشاء مصفوفة فارغة بنفس شكل d باستخدام np.empty
f = np.empty_like(d)

# طباعة الشكل للتأكد
print("شكل f:", f.shape)


NameError: name 'd' is not defined




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [47]:
import numpy as np

f = np.empty_like(d)

d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)

f[d == d_min] = 0
f[(d > d_min) & (d < d_mean)] = 25
f[d == d_mean] = 50
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_max] = 100
print(f)



NameError: name 'd' is not defined





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [49]:
# طباعة القيم الأصلية في d
print("Array d:")
print(d)

# طباعة القيم التي تم تعيينها في f
print("\nArray f:")
print(f)



Array d:


NameError: name 'd' is not defined

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [50]:
# إنشاء مصفوفة بنفس شكل d ولكن تحتوي على قيم نصية بدلاً من الأرقام
f = [[[None for _ in range(d.shape[2])] for _ in range(d.shape[1])] for _ in range(d.shape[0])]

# تطبيق الشروط باستخدام الحلقات العادية
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] == d_min:
                f[i][j][k] = 'A'
            elif d[i][j][k] < d_mean:
                f[i][j][k] = 'B'
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 'C'
            elif d[i][j][k] < d_max:
                f[i][j][k] = 'D'
            else:
                f[i][j][k] = 'E'

# طباعة النتيجة
for layer in f:
    print(layer)


NameError: name 'd' is not defined